
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Dev Empathy Book Club
subtitle: "Better Developers. Better People."
url: "http://dev-empathy-book-club.github.io" # the base hostname & protocol for your site
baseurl: ""
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: episodes
    desc: "Panel discussions so far!"

collections:
  posts:
    permalink: /episodes/:slug
