
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Dev Empathy Book Club
subtitle: "Better Developers. Better People."
url: "https://devempathybook.club" # the base hostname & protocol for your site
baseurl: ""
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: episodes
    desc: "Panel discussions so far!"

  - cat: stories
    desc: "Your turn to share your #DevEmpathy stories!"

collections:
  stories:
    output: true
    permalink: '/stories/:slug'
  episodes:
    output: true
    permalink: '/episodes/:slug'
